package io.riddles.javainterface.exception;

/**
 * io.riddles.javainterface.exception.InvalidMoveException - Created on 3-6-16
 *
 * DO NOT EDIT THIS FILE
 *
 *
 * @author Joost - jim@riddles.io
 */
public class ConfigurationException extends RuntimeException {

    public ConfigurationException(final String message) {
        super(message);
    }

    public ConfigurationException(final String message, final Throwable cause) {
        super(message, cause);
    }

    public ConfigurationException(final Throwable cause) {
        super(cause.getMessage(), cause);
    }
}
