package io.riddles.javainterface.exception;

/**
 * io.riddles.javainterface.exception.InvalidMoveException - Created on 3-6-16
 *
 * DO NOT EDIT THIS FILE
 *
 *
 * @author Joost - jim@riddles.io
 */
public class InvalidInputException extends Exception {

    public InvalidInputException(String message) {
        super(message);
    }

    @Override
    public String getMessage() {
        return "Invalid input: " + super.getMessage();
    }
}
