package io.riddles.javainterface.exception;

/**
 * io.riddles.javainterface.exception.InvalidMoveException - Created on 3-6-16
 *
 * DO NOT EDIT THIS FILE
 *
 * @author Jim - jim@riddles.io
 */
public class InvalidMoveException extends Exception {

    public InvalidMoveException(String message) {
        super(message);
    }

    @Override
    public String getMessage() {
        return "Invalid move: " + super.getMessage();
    }
}
